In [ ]:
# default_exp module16

# Import

In [ ]:
# export
import numpy as np
import matplotlib.pyplot as plt

from cs371.utils import *

# Utilities

In [ ]:
def is_sorted(X):
    for i in range(len(X)-1):
        if X[i+1] < X[i]:
            return False
    return True

# Bucket Sort

Assume X is bounded between [0, 9]

In [ ]:
def bucket_sort(X):
    buckets = np.zeros(len(X), dtype=np.int_)
    for x in X:
        buckets[x] += 1
    return sum([[x for _ in range(count)] for x, count in enumerate(buckets)], [])

In [ ]:
X = [1, 4, 2, 9, 4, 3, 0, 2, 8, 4]

In [ ]:
bucket_sort(X)

[0, 1, 2, 2, 3, 4, 4, 4, 8, 9]

# Radix Sort

In [ ]:
def get_base10(x, place):
    return x//(10**place) % 10

In [ ]:
x = 5174
get_base10(x, 0), get_base10(x, 1), get_base10(x, 2), get_base10(x, 3)

(4, 7, 1, 5)

In [ ]:
def max_place(x): 
    if    x == 0: return 0
    else:         return int(np.log10(x))+1

In [ ]:
max_place(10_000), max_place(9_999), max_place(99), max_place(1), max_place(0)

(5, 4, 2, 1, 0)

In [ ]:
def max_place_arr(X):
    return max([max_place(x) for x in X])

In [ ]:
X = [123, 234, 48, 3948, 3, 21]
max_place_arr(X)

4

In [ ]:
def _radix_sort(X, idx1, idx2, place, buf_X):
    if place < 0:
        return
    
    # Get histogram of radices
    buf_radix = np.zeros(10, dtype=int)
    for idx in range(idx1, idx2+1):
        buf_radix[get_base10(X[idx], place)] += 1
    
    # Use cumsum to get starting index of each radix
    buf_radix[1:] = np.cumsum(buf_radix[:-1]) + idx1
    buf_radix[0]  = idx1
    
    # Copy elements into buffer in sorted order
    for idx in range(idx1, idx2+1):
        bucket = get_base10(X[idx], place)
        idx_buf = buf_radix[bucket]
        buf_X[idx_buf] = X[idx]
        buf_radix[bucket] += 1
        
    # Copy elements from buffer back into array
    X[idx1:idx2+1] = buf_X[idx1:idx2+1]
    
    # Recursively sort each radix
    for radix in range(10):
        if radix > 0: 
            idx1 = buf_radix[radix-1]
        idx2 = buf_radix[radix]-1
        if idx2 > idx1:          
            _radix_sort(X, idx1, idx2, place-1, buf_X)

The issue with this is `buf_radix` needs to be allocated each time, since recursive call will overwrite the buffer if we keep trackof it

In [ ]:
X          = [123, 234, 48, 3948, 3, 21]
place      = 3
idx1       = 0
idx2       = len(X)-1
buf_X      = np.zeros_like(X)

In [ ]:
_radix_sort(X, 0, len(X)-1, place, buf_X)
X

[3, 21, 48, 123, 234, 3948]

In [ ]:
def radix_sort(X):
    place      = max_place_arr(X)-1
    idx1       = 0
    idx2       = len(X)-1
    buf_X      = np.zeros_like(X)
    _radix_sort(X, 0, len(X)-1, place, buf_X)
    return X

In [ ]:
X = [123, 234, 48, 3948, 3, 21]

In [ ]:
radix_sort(X)

[3, 21, 48, 123, 234, 3948]

In [ ]:
is_sorted(X)

True

In [ ]:
X = np.random.randint(1e4, size=100)
X

array([8187,  958, 5422, 6270, 1367, 6372, 7353, 3691, 2262, 6202, 5169,
       4944,   37, 5522, 2155, 1136, 9034, 3839, 7120, 4511, 5680,  480,
       8506, 6012, 7195, 2710, 2521, 3516, 7160, 2753, 2787, 5494, 6151,
       5874, 8122, 7022, 6986, 1302,  466, 2404, 3510, 2258, 7962, 7245,
       3162, 2102, 6246, 5585, 4288, 9183, 9886, 7404, 4107, 1816, 4873,
       9564, 6171, 7719, 6733, 9033, 8560, 1585,  796, 2102, 9202, 6616,
       6086, 3057, 3355, 2899, 2238, 4619,  964, 3362, 5185, 5518, 9536,
       2470, 4633, 3492, 1754, 2314, 8267, 4306, 5119, 3500, 9062, 4807,
       9904, 3200, 3965, 1353, 5298, 9662, 9305, 9609, 2472, 4247, 1349,
       2306])

In [ ]:
radix_sort(X)

array([  37,  466,  480,  796,  958,  964, 1136, 1302, 1349, 1353, 1367,
       1585, 1754, 1816, 2102, 2102, 2155, 2238, 2258, 2262, 2306, 2314,
       2404, 2470, 2472, 2521, 2710, 2753, 2787, 2899, 3057, 3162, 3200,
       3355, 3362, 3492, 3500, 3510, 3516, 3691, 3839, 3965, 4107, 4247,
       4288, 4306, 4511, 4619, 4633, 4807, 4873, 4944, 5119, 5169, 5185,
       5298, 5422, 5494, 5518, 5522, 5585, 5680, 5874, 6012, 6086, 6151,
       6171, 6202, 6246, 6270, 6372, 6616, 6733, 6986, 7022, 7120, 7160,
       7195, 7245, 7353, 7404, 7719, 7962, 8122, 8187, 8267, 8506, 8560,
       9033, 9034, 9062, 9183, 9202, 9305, 9536, 9564, 9609, 9662, 9886,
       9904])

In [ ]:
is_sorted(X)

True

# Try doing least significant digit first

In [ ]:
def _radix_sort2(X, place, buf_X, buf_radix):
    # Get histogram of radices
    buf_radix[:] = 0
    for idx in range(len(X)):
        buf_radix[get_base10(X[idx], place)] += 1
    
    # Use cumsum to get starting index of each radix
    buf_radix[1:] = np.cumsum(buf_radix[:-1])
    buf_radix[0]  = 0
    
    # Copy elements into buffer in sorted order
    for idx in range(len(X)):
        bucket = get_base10(X[idx], place)
        idx_buf = buf_radix[bucket]
        buf_X[idx_buf] = X[idx]
        buf_radix[bucket] += 1
        
    # Copy elements from buffer back into array
    X[:] = buf_X[:]
    return X

In [ ]:
X = [123, 234, 48, 3948, 3, 21]

In [ ]:
place      = max_place_arr(X)-1
buf_X      = np.zeros_like(X)
buf_radix  = np.zeros(10, dtype=int)

In [ ]:
_radix_sort2(X, 0, buf_X, buf_radix)

[21, 123, 3, 234, 48, 3948]

In [ ]:
_radix_sort2(X, 1, buf_X, buf_radix)

[3, 21, 123, 234, 48, 3948]

In [ ]:
_radix_sort2(X, 2, buf_X, buf_radix)

[3, 21, 48, 123, 234, 3948]

In [ ]:
_radix_sort2(X, 3, buf_X, buf_radix)

[3, 21, 48, 123, 234, 3948]

In [ ]:
def radix_sort2(X):
    buf_X      = np.zeros_like(X)
    buf_radix  = np.zeros(10, dtype=int)
    for place in range(max_place_arr(X)):
        X = _radix_sort2(X, place, buf_X, buf_radix)
    return X

In [ ]:
X = [123, 234, 48, 3948, 3, 21]

In [ ]:
X = radix_sort2(X)
X

[3, 21, 48, 123, 234, 3948]

In [ ]:
is_sorted(X)

True

In [ ]:
X = np.random.randint(1e4, size=100)
X

array([7057, 8982, 6606, 6981, 8727, 5004, 5536, 8577, 9979, 8290, 3230,
       4188,  135, 3380, 4856, 9121, 3749, 5426, 2633, 7474, 2869, 5670,
       7336, 9965, 3115, 5781,   66, 7842, 2676, 5213, 9921, 1885, 7811,
       9818, 1399, 9948, 6199, 6503, 9580, 5273, 2707, 4139, 5125, 7785,
       4224, 5791, 1493, 4056, 7134, 7650, 8797, 6164, 1640, 5129, 8599,
       1867, 8935,  786,  652, 8848, 2841, 4881, 7322, 8157, 5493, 3304,
       5568, 1539, 3963,  161, 2815, 3510, 2841, 1173, 7191, 7438, 6429,
       7577, 2329, 1891, 3405, 9744, 8371,  786, 4641, 8996,  198, 7945,
       5536, 8184, 5451, 6427, 2269, 3993, 1594,  667, 6082, 3244, 9455,
       8738])

In [ ]:
X = radix_sort2(X)
X

array([  66,  135,  161,  198,  652,  667,  786,  786, 1173, 1399, 1493,
       1539, 1594, 1640, 1867, 1885, 1891, 2269, 2329, 2633, 2676, 2707,
       2815, 2841, 2841, 2869, 3115, 3230, 3244, 3304, 3380, 3405, 3510,
       3749, 3963, 3993, 4056, 4139, 4188, 4224, 4641, 4856, 4881, 5004,
       5125, 5129, 5213, 5273, 5426, 5451, 5493, 5536, 5536, 5568, 5670,
       5781, 5791, 6082, 6164, 6199, 6427, 6429, 6503, 6606, 6981, 7057,
       7134, 7191, 7322, 7336, 7438, 7474, 7577, 7650, 7785, 7811, 7842,
       7945, 8157, 8184, 8290, 8371, 8577, 8599, 8727, 8738, 8797, 8848,
       8935, 8982, 8996, 9121, 9455, 9580, 9744, 9818, 9921, 9948, 9965,
       9979])

In [ ]:
is_sorted(X)

True

# Build

In [ ]:
build_notebook()

<IPython.core.display.Javascript object>

Converted module16.ipynb.
