In [ ]:
# default_exp module16

# Import

In [ ]:
# export
import numpy as np
import matplotlib.pyplot as plt

from cs371.utils import *

# Utilities

In [ ]:
def is_sorted(X):
    for i in range(len(X)-1):
        if X[i+1] < X[i]:
            return False
    return True

# Bucket Sort

Assume X is bounded between [0, 9]

In [ ]:
def bucket_sort(X):
    buckets = np.zeros(len(X), dtype=np.int_)
    for x in X:
        buckets[x] += 1
    return sum([[x for _ in range(count)] for x, count in enumerate(buckets)], [])

In [ ]:
X = [1, 4, 2, 9, 4, 3, 0, 2, 8, 4]

In [ ]:
bucket_sort(X)

[0, 1, 2, 2, 3, 4, 4, 4, 8, 9]

# Radix Sort

In [ ]:
def get_base10(x, place):
    return x//(10**place) % 10

In [ ]:
x = 5174
get_base10(x, 0), get_base10(x, 1), get_base10(x, 2), get_base10(x, 3)

(4, 7, 1, 5)

In [ ]:
def max_place(x): 
    if    x == 0: return 0
    else:         return int(np.log10(x))+1

In [ ]:
max_place(10_000), max_place(9_999), max_place(99), max_place(1), max_place(0)

(5, 4, 2, 1, 0)

In [ ]:
def max_place_arr(X):
    return max([max_place(x) for x in X])

In [ ]:
X = [123, 234, 48, 3948, 3, 21]
max_place_arr(X)

4

In [ ]:
def _radix_sort(X, idx1, idx2, place, buf_X):
    if place < 0:
        return
    
    # Get histogram of radices
    buf_radix = np.zeros(10, dtype=int)
    for idx in range(idx1, idx2+1):
        buf_radix[get_base10(X[idx], place)] += 1
    
    # Use cumsum to get starting index of each radix
    buf_radix[1:] = np.cumsum(buf_radix[:-1]) + idx1
    buf_radix[0]  = idx1
    
    # Copy elements into buffer in sorted order
    for idx in range(idx1, idx2+1):
        bucket = get_base10(X[idx], place)
        idx_buf = buf_radix[bucket]
        buf_X[idx_buf] = X[idx]
        buf_radix[bucket] += 1
        
    # Copy elements from buffer back into array
    X[idx1:idx2+1] = buf_X[idx1:idx2+1]
    
    # Recursively sort each radix
    for radix in range(10):
        if radix > 0: 
            idx1 = buf_radix[radix-1]
        idx2 = buf_radix[radix]-1
        if idx2 > idx1:          
            _radix_sort(X, idx1, idx2, place-1, buf_X)

The issue with this is `buf_radix` needs to be allocated each time, since recursive call will overwrite the buffer if we keep trackof it

In [ ]:
X          = [123, 234, 48, 3948, 3, 21]
place      = 3
idx1       = 0
idx2       = len(X)-1
buf_X      = np.zeros_like(X)

In [ ]:
_radix_sort(X, 0, len(X)-1, place, buf_X)
X

[3, 21, 48, 123, 234, 3948]

In [ ]:
def radix_sort(X):
    place      = max_place_arr(X)-1
    idx1       = 0
    idx2       = len(X)-1
    buf_X      = np.zeros_like(X)
    _radix_sort(X, 0, len(X)-1, place, buf_X)
    return X

In [ ]:
X = [123, 234, 48, 3948, 3, 21]

In [ ]:
radix_sort(X)

[3, 21, 48, 123, 234, 3948]

In [ ]:
is_sorted(X)

True

In [ ]:
X = np.random.randint(1e4, size=100)
X

array([2888, 7504, 8218, 5678, 3278, 5957, 2967, 7453, 2034,  270, 7919,
       2977, 3783, 4089, 5011, 7778, 1889, 9653, 2631, 9621, 2411, 6118,
       3551, 7086, 4536, 6297, 7419, 3017, 5570, 7612, 9652, 4496, 5235,
       6949, 4350, 9997, 3233, 2809, 4627, 7350, 6866, 6659, 9083, 3442,
       7948, 3430, 4072,   44, 2835, 2578, 1995,  167, 8677, 1086, 2299,
       2762, 2984, 7680, 4352, 1930, 1243, 7363, 2370,  484, 5395, 1327,
       6054, 9425, 4641, 2284, 9958, 3010, 6005, 7787, 6814, 7465, 8942,
       3903, 4167, 2829, 2304, 1502, 1069, 7586, 8895, 6571, 9659, 4175,
       4293, 6630, 1567, 3498, 7987, 6770, 7141, 7770, 9153, 5794, 3527,
       4373])

In [ ]:
radix_sort(X)

array([  44,  167,  270,  484, 1069, 1086, 1243, 1327, 1502, 1567, 1889,
       1930, 1995, 2034, 2284, 2299, 2304, 2370, 2411, 2578, 2631, 2762,
       2809, 2829, 2835, 2888, 2967, 2977, 2984, 3010, 3017, 3233, 3278,
       3430, 3442, 3498, 3527, 3551, 3783, 3903, 4072, 4089, 4167, 4175,
       4293, 4350, 4352, 4373, 4496, 4536, 4627, 4641, 5011, 5235, 5395,
       5570, 5678, 5794, 5957, 6005, 6054, 6118, 6297, 6571, 6630, 6659,
       6770, 6814, 6866, 6949, 7086, 7141, 7350, 7363, 7419, 7453, 7465,
       7504, 7586, 7612, 7680, 7770, 7778, 7787, 7919, 7948, 7987, 8218,
       8677, 8895, 8942, 9083, 9153, 9425, 9621, 9652, 9653, 9659, 9958,
       9997])

In [ ]:
is_sorted(X)

True

# Try doing least significant digit first

In [ ]:
def _radix_sort2(X, place, buf_X, buf_radix):
    # Get histogram of radices
    buf_radix[:] = 0
    for idx in range(len(X)):
        buf_radix[get_base10(X[idx], place)] += 1
    
    # Use cumsum to get starting index of each radix
    buf_radix[1:] = np.cumsum(buf_radix[:-1])
    buf_radix[0]  = 0
    
    # Copy elements into buffer in sorted order
    for idx in range(len(X)):
        bucket = get_base10(X[idx], place)
        idx_buf = buf_radix[bucket]
        buf_X[idx_buf] = X[idx]
        buf_radix[bucket] += 1
        
    # Copy elements from buffer back into array
    X[:] = buf_X[:]
    return X

In [ ]:
X = [123, 234, 48, 3948, 3, 21]

In [ ]:
place      = max_place_arr(X)-1
buf_X      = np.zeros_like(X)
buf_radix  = np.zeros(10, dtype=int)

In [ ]:
_radix_sort2(X, 0, buf_X, buf_radix)

[21, 123, 3, 234, 48, 3948]

In [ ]:
_radix_sort2(X, 1, buf_X, buf_radix)

[3, 21, 123, 234, 48, 3948]

In [ ]:
_radix_sort2(X, 2, buf_X, buf_radix)

[3, 21, 48, 123, 234, 3948]

In [ ]:
_radix_sort2(X, 3, buf_X, buf_radix)

[3, 21, 48, 123, 234, 3948]

In [ ]:
def radix_sort2(X):
    buf_X      = np.zeros_like(X)
    buf_radix  = np.zeros(10, dtype=int)
    for place in range(max_place_arr(X)):
        X = _radix_sort2(X, place, buf_X, buf_radix)
    return X

In [ ]:
X = [123, 234, 48, 3948, 3, 21]

In [ ]:
X = radix_sort2(X)
X

[3, 21, 48, 123, 234, 3948]

In [ ]:
is_sorted(X)

True

In [ ]:
X = np.random.randint(1e4, size=100)
X

array([8185, 2835, 9914, 3653, 3990, 4262,  777, 3266, 3432, 4531, 4240,
        481,  104, 7163, 1088, 5456, 9847, 3778, 1288, 2359, 7517, 5223,
       5570, 7584, 1168,  342, 7900, 8179, 5033, 8845, 5522, 4008, 4270,
       3760, 4084, 2491, 9956, 5687, 7908, 4513, 2108, 5540, 5871, 6434,
       4508, 4863, 7565, 7620,  125, 4459,  888, 7304, 4284, 4675, 1210,
       5502,  475, 6398, 9190, 7051, 9722, 3524, 7895, 2356, 2281, 8947,
       4777, 4623, 5184,   29, 7737, 3397, 5684, 9264, 4995, 9027, 1249,
       9002, 5670, 6621, 9685, 7160, 9234, 6871, 8589, 3153, 7335, 9368,
        781, 3344, 8899, 2724, 4467, 9453, 3100, 1746, 1531, 3236, 2737,
       8118])

In [ ]:
X = radix_sort2(X)
X

array([  29,  104,  125,  342,  475,  481,  777,  781,  888, 1088, 1168,
       1210, 1249, 1288, 1531, 1746, 2108, 2281, 2356, 2359, 2491, 2724,
       2737, 2835, 3100, 3153, 3236, 3266, 3344, 3397, 3432, 3524, 3653,
       3760, 3778, 3990, 4008, 4084, 4240, 4262, 4270, 4284, 4459, 4467,
       4508, 4513, 4531, 4623, 4675, 4777, 4863, 4995, 5033, 5184, 5223,
       5456, 5502, 5522, 5540, 5570, 5670, 5684, 5687, 5871, 6398, 6434,
       6621, 6871, 7051, 7160, 7163, 7304, 7335, 7517, 7565, 7584, 7620,
       7737, 7895, 7900, 7908, 8118, 8179, 8185, 8589, 8845, 8899, 8947,
       9002, 9027, 9190, 9234, 9264, 9368, 9453, 9685, 9722, 9847, 9914,
       9956])

In [ ]:
is_sorted(X)

True

# Permutation and fisher yates shuffling

In [ ]:
def swap(X, i, j): X[i], X[j] = X[j], X[i]

In [ ]:
def perm(X, idx=0):
    if idx == len(X)-1:
        print(X)
    else:
        for i in range(idx, len(X)):
            swap(X, idx, i)
            perm(X, idx+1)
            swap(X, i, idx)

In [ ]:
perm([1,2,3])

[1, 2, 3]
[1, 3, 2]
[2, 1, 3]
[2, 3, 1]
[3, 2, 1]
[3, 1, 2]


In [ ]:
def fisher_yates(X):
    for i in range(len(X)-1, 0, -1):
        print(i)
        j = np.random.randint(i+1)
        swap(X, i, j)
    return(X)

In [ ]:
X = [1, 2, 3]

In [ ]:
fisher_yates(X)

2
1


[3, 1, 2]

# Build

In [ ]:
build_notebook()

<IPython.core.display.Javascript object>

Converted module16.ipynb.
